### ISSUE TITLE
Split a file in two

### ISSUE THREAD

**Issue by BillSpyro** [Thommond/Command-line-war#2]
https://github.com/Thommond/Command-line-war/blob/ece36eaebcf9066178cc63a7e892d571735baa3b/items.py#L2

This file is named items but some of the classes in here aren't necessarily items. Some are in relation to the player. So I suggest making a new file that deals with the characters and put everything the pertains to the player and enemies in there instead.

**Comment by Thommond** [comment]
Thanks a lot, I split the file into two. It makes logistical sense to me.
